
project_id = "ijplrwyidnrqjlgyhdhs"

[functions.create-checkout-session]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.dynamic-service]
verify_jwt = true

[functions.finalize-youtube-upload]
verify_jwt = true

[functions.initiate-youtube-upload]
verify_jwt = true

[functions.get-youtube-stats]
verify_jwt = true

[functions.get-youtube-channel]
verify_jwt = true
