
project_id = "ijplrwyidnrqjlgyhdhs"

[functions.create-checkout-session]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.dynamic-service]
verify_jwt = true

[functions.finalize-youtube-upload]
verify_jwt = true

[functions.initiate-youtube-upload]
verify_jwt = true

[functions.get-youtube-stats]
verify_jwt = true

[functions.get-youtube-channel]
verify_jwt = true

[functions.generate-script]
verify_jwt = true

[functions.generate-descriptions]
verify_jwt = true

[functions.generate-description]
verify_jwt = true

[functions.generate-ideas]
verify_jwt = true

[functions.generate-hashtags]
verify_jwt = true

[functions.generate-linkedin-posts]
verify_jwt = true

[functions.generate-reddit-posts]
verify_jwt = true

[functions.verify-payment]
verify_jwt = true
