// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ijplrwyidnrqjlgyhdhs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlqcGxyd3lpZG5ycWpsZ3loZGhzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEyNzQ5ODIsImV4cCI6MjA1Njg1MDk4Mn0.kiO1SeL_GGJG4ZuBfod7BJRkyAUHJ54E1KeGsAziBwo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);